config/routes.rb
Rails.application.routes.draw do
  resources :so_shipments
  resources :so_pick_lists
  resources :order_lines
  resources :sales_orders
  resources :inventory_items
  resources :order_statuses
  resources :customer_accounts

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'

end

app/models/inventory_item.rb
class InventoryItem < ActiveRecord::Base
   has_many :order_lines
   has_many :sales_orders, through: :order_lines
end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  before_action :set_inventory_item, only: [:show, :edit, :update, :destroy]

  # GET /inventory_items
  # GET /inventory_items.json
  def index
    @inventory_items = InventoryItem.all
  end

  # GET /inventory_items/1
  # GET /inventory_items/1.json
  def show
  end

  # GET /inventory_items/new
  def new
    @inventory_item = InventoryItem.new
  end

  # GET /inventory_items/1/edit
  def edit
  end

  # POST /inventory_items
  # POST /inventory_items.json
  def create
    @inventory_item = InventoryItem.new(inventory_item_params)

    respond_to do |format|
      if @inventory_item.save
        flash[:success] = "Inventory item was successfully created."
        format.html { redirect_to @inventory_item }
        format.json { render :show, status: :created, location: @inventory_item }
      else
        format.html { render :new }
        format.json { render json: @inventory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventory_items/1
  # PATCH/PUT /inventory_items/1.json
  def update
    respond_to do |format|
      if @inventory_item.update(inventory_item_params)
        format.html { redirect_to @inventory_item, notice: 'Inventory item was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory_item }
      else
        format.html { render :edit }
        format.json { render json: @inventory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_items/1
  # DELETE /inventory_items/1.json
  def destroy
    @inventory_item.destroy
    respond_to do |format|
      format.html { redirect_to inventory_items_url, notice: 'Inventory item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory_item
      @inventory_item = InventoryItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_item_params
      params.require(:inventory_item).permit(:barcode, :product_name, :description, :selling_price, :unit_of_measure, :qty_on_hand, :location_aisle, :location_area)
    end
end

app/helpers/inventory_items_helper.rb
module InventoryItemsHelper
end

app/views/inventory_items/_form.html.erb
<%= form_for(@inventory_item) do |f| %>
  <% if @inventory_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory_item.errors.count, "error") %> prohibited this inventory_item from being saved:</h2>

      <ul>
      <% @inventory_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :barcode %><br>
    <%= f.number_field :barcode %>
  </div>
  <div class="field">
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :selling_price %><br>
    <%= f.text_field :selling_price %>
  </div>
  <div class="field">
    <%= f.label :unit_of_measure %><br>
    <%= f.text_field :unit_of_measure %>
  </div>
  <div class="field">
    <%= f.label :qty_on_hand %><br>
    <%= f.number_field :qty_on_hand %>
  </div>
  <div class="field">
    <%= f.label :location_aisle %><br>
    <%= f.number_field :location_aisle %>
  </div>
  <div class="field">
    <%= f.label :location_area %><br>
    <%= f.text_field :location_area %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventory_items/edit.html.erb
<h1>Editing Inventory Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory_item %> |
<%= link_to 'Back', inventory_items_path %>

app/views/inventory_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Inventory Items</h1>

<table class="table table-striped table-condensed" >
  <thead>
    <tr>
      <th>ID</th>
      <th>Barcode</th>
      <th>Product name</th>
      <th>Description</th>
      <th>Selling price</th>
      <th>Unit of measure</th>
      <th>Qty on hand</th>
      <th>Location aisle</th>
      <th>Location area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventory_items.each do |inventory_item| %>
      <tr>
        <td><%= inventory_item.id %></td>
        <td><%= inventory_item.barcode %></td>
        <td><%= inventory_item.product_name %></td>
        <td><%= inventory_item.description %></td>
        <td><%= inventory_item.selling_price %></td>
        <td><%= inventory_item.unit_of_measure %></td>
        <td><%= inventory_item.qty_on_hand %></td>
        <td><%= inventory_item.location_aisle %></td>
        <td><%= inventory_item.location_area %></td>
        <td><%= link_to 'Show', inventory_item %></td>
        <td><%= link_to 'Edit', edit_inventory_item_path(inventory_item) %></td>
        <td><%= link_to 'Destroy', inventory_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory item', new_inventory_item_path %>

app/views/inventory_items/new.html.erb
<h1>New Inventory Item</h1>

<%= render 'form' %>

<%= link_to 'Back', inventory_items_path %>

app/views/inventory_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Barcode:</strong>
  <%= @inventory_item.barcode %>
</p>

<p>
  <strong>Product name:</strong>
  <%= @inventory_item.product_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @inventory_item.description %>
</p>

<p>
  <strong>Selling price:</strong>
  <%= @inventory_item.selling_price %>
</p>

<p>
  <strong>Unit of measure:</strong>
  <%= @inventory_item.unit_of_measure %>
</p>

<p>
  <strong>Qty on hand:</strong>
  <%= @inventory_item.qty_on_hand %>
</p>

<p>
  <strong>Location aisle:</strong>
  <%= @inventory_item.location_aisle %>
</p>

<p>
  <strong>Location area:</strong>
  <%= @inventory_item.location_area %>
</p>

<%= link_to 'Edit', edit_inventory_item_path(@inventory_item) %> |
<%= link_to 'Back', inventory_items_path %>