config/routes.rb
Rails.application.routes.draw do
  resources :so_shipments
  resources :so_pick_lists
  resources :order_lines
  resources :sales_orders
  resources :inventory_items
  resources :order_statuses
  resources :customer_accounts

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'

end

app/models/customer_account.rb
class CustomerAccount < ActiveRecord::Base
   has_many :sales_orders, :dependent => :destroy

   validates :email, confirmation: true
   # validates :email_confirmation, presence: true
   
   validates :fname, length: { maximum: 26 }, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }, presence: true
   validates :middle_initial, length: { maximum: 1 }, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }, presence: true
   validates :lname, length: { maximum: 26 }, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }, presence: true

   validates :street_add, length: { maximum: 81 }, presence: true
   validates :city, length: { maximum: 26 }, presence: true
   validates :zipcode, length: { maximum: 5 }, numericality: { only_integer: true }, presence: true

   validates :home_phone, length: { maximum: 20 }, numericality: { only_integer: true }
   validates :cell_phone, length: { maximum: 20 }, numericality: { only_integer: true }, presence: true
end

app/controllers/customer_accounts_controller.rb
class CustomerAccountsController < ApplicationController
  before_action :set_customer_account, only: [:show, :edit, :update, :destroy]
  before_filter :check_for_cancel, :only => [:create, :update]

def check_for_cancel
  if params[:commit] == "Cancel"
    redirect_to new_customer_account_url
  end
end

  # GET /customer_accounts
  # GET /customer_accounts.json

  def index
    @customer_accounts = CustomerAccount.paginate(page: params[:page])
  end

  # GET /customer_accounts/1
  # GET /customer_accounts/1.json
  def show
  end

  # GET /customer_accounts/new
  def new
    @customer_account = CustomerAccount.new
  end

  # GET /customer_accounts/1/edit
  def edit
  end

  # POST /customer_accounts
  # POST /customer_accounts.json
  def create
    @customer_account = CustomerAccount.new(customer_account_params)

    respond_to do |format|
      if @customer_account.save
        flash[:success] = "Customer account was successfully created!"
        format.html { redirect_to @customer_account }
        format.json { render :show, status: :created, location: @customer_account }
      else
        format.html { render :new }
        format.json { render json: @customer_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_accounts/1
  # PATCH/PUT /customer_accounts/1.json
  def update
    respond_to do |format|
      if @customer_account.update(customer_account_params)
        flash[:success] = "Customer account was successfully updated!"
        format.html { redirect_to @customer_account }
        format.json { render :show, status: :ok, location: @customer_account }
      else
        format.html { render :edit }
        format.json { render json: @customer_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_accounts/1
  # DELETE /customer_accounts/1.json
  def destroy
    @customer_account.destroy
    respond_to do |format|
      format.html { redirect_to customer_accounts_url, notice: 'Customer account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_account
      @customer_account = CustomerAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_account_params
      params.require(:customer_account).permit(:fname, :middle_initial, :lname, :street_add, :city, :state, :zipcode, :email, :home_phone, :cell_phone, :phone_pref, :password)
    end
end

app/helpers/customer_accounts_helper.rb
module CustomerAccountsHelper
end

app/views/customer_accounts/_customer_accounts.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/customer_accounts/_form.html.erb
<%= form_for(@customer_account) do |f| %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= render 'shared/error_messages', object: f.object %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 col-md-offset-2">
        <%= f.label :fname, "First Name*" %>
        <%= f.text_field :fname, class: 'form-control' %>
    </div>
    <div class="col-md-2 col-sm-offset-0">
        <%= f.label :middle_initial, "Middle Initial" %>
        <%= f.text_field :middle_initial, class: 'form-control' %>
    </div>
    <div class="col-md-3 col-md-offset-0">
        <%= f.label :lname, "Last Name*" %>
        <%= f.text_field :lname, class: 'form-control' %>
    </div>
    <div class="col-md-2 col-md-offset-0">* required field
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
        <%= f.label :street_add, "Street Address*" %>
        <%= f.text_field :street_add, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3 col-md-offset-2">
        <%= f.label :city, "City*" %>
        <%= f.text_field :city, class: 'form-control' %>
    </div>  
    <div class="col-md-3 col-md-offset-0">
        <div class="form-group">
          <%= f.label :state, "State*" %>
          <%= f.select(:state, options_for_select(["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District Of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]), {}, {class: "form-control"}) %>
        </div>
    </div>
    <div class="col-md-2 col-md-offset-0">
        <%= f.label :zipcode, "Zip Code*" %>
        <%= f.text_field :zipcode, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3 col-md-offset-2">
        <%= f.label :home_phone, "Home Phone" %>
        <%= f.text_field :home_phone, class: 'form-control' %>
    </div>
    <div class="col-md-3 col-md-offset-0">      
        <%= f.label :cell_phone, "Cell Phone*" %>
        <%= f.text_field :cell_phone, class: 'form-control' %>
    </div>
    <div class="col-md-2 col-md-offset-0">   
      <div class="form-group">
        <%= f.label :phone_pref, "Preferred Phone*" %>
        <%= f.select(:phone_pref, options_for_select(["Home phone", "Cell Phone"]), {}, {class: "form-control"}) %>
      </div>
    </div>
  </div>
      
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <br><br>
    </div>
  </div>
    
  <div class="row">
    <div class="col-md-4 col-md-offset-2">
        <%= f.label :email, "Email*"%>
        <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="col-md-4 col-md-offset-0">
        <%= f.label :email_confirmation, "Email confirmation*" %>
        <%= f.email_field :email_confirmation, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 col-md-offset-2">
        <%= f.label :password, "Password*" %>
        <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="col-md-4 col-md-offset-0">
        <%= f.label :password_confirmation, "Password Confirmation*" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <div class="col-md-4 col-md-offset-2">
        <%= f.submit "Cancel", class: "btn btn-danger" %>
    </div>
    <div class="col-md-4 col-md-offset-0">
        <button type="button" id="submitBtn" class="btn btn-success btn-block" data-toggle="modal" data-target="#myModal">Create my account</button>
    </div>

<!-- confirmaiton modal starts here -->

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Does everything look right?</h4>
        </div>
        <div class="modal-body">
            <p>
              <strong>Name:</strong>
              <span id="fname"></span> <span id="middle_initial"></span> <span id="lname"></span>
            </p>

            <p>
              <strong>Adress:</strong>
              <span id="street_add"></span>, <span id="city"></span>, <span id="state"></span> <span id="zipcode"></span>
            </p>

            <p>
              <strong>Email:</strong>
              <span id="email"</span>
            </p>

            <p>
              <strong>Home phone:</strong>
              <span id="home_phone"</span>
            </p>

            <p>
              <strong>Cell phone:</strong>
              <span id="cell_phone"</span>
            </p>

            <p>
              <strong>Phone preference:</strong>
              <span id="phone_pref"</span>
            </p>
         </div>
        <div class="modal-footer" style="border: none">
          <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
          <button class="btn btn-success">Yes</button>
        </div>
      </div>
    </div>

   </div>
  </div>

<% end %>

app/views/customer_accounts/edit.html.erb
<h1>Editing Customer Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer_account %> |
<%= link_to 'Back', customer_accounts_path %>

app/views/customer_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
<div class="row">
  <div class="col-md-3 col-md-offset-0">
    <%= link_to 'Create New Account', new_customer_account_path, class: "btn btn-success" %>
  </div>
  <div class="col-md-5 col-md-offset-1">
    <h1>All Customer Accounts</h1>
  </div>
  <div class="col-md-4 col-md-offset-0">
   <%= will_paginate %> 
  </div>
</div>


<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Customer ID</th>
      <th>First Name</th>
      <th>M.I.</th>
      <th>Last Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip Code</th>
      <th>Email</th>
      <th>Home phone</th>
      <th>Cell phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_accounts.each do |customer_account| %>
      <tr>
        <td><%= customer_account.id %></td>
        <td><%= customer_account.fname %></td>
        <td><%= customer_account.middle_initial %></td>
        <td><%= customer_account.lname %></td>
        <td><%= customer_account.street_add %></td>
        <td><%= customer_account.city %></td>
        <td><%= customer_account.state %></td>
        <td><%= customer_account.zipcode %></td>
        <td><%= customer_account.email %></td>
        <td><%= customer_account.home_phone %></td>
        <td><%= customer_account.cell_phone %></td>
          <div class="btn-group-xs">
            <td><%= link_to 'Show', customer_account, class: "btn btn-primary" %></td>
            <td><%= link_to 'Edit', edit_customer_account_path(customer_account), class: "btn btn-primary" %></td>
            <td><%= link_to 'Destroy', customer_account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
          </div>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate %>
</div>

app/views/customer_accounts/new.html.erb
<% provide(:title, 'Create New Account') %>

<h1>Create New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/customer_accounts/show.html.erb
<p id="notice"><%= notice %></p>
<br><br><br>
<div class="row">
   <div class="col-md-4 col-md-offset-0" style="border: 1px solid black; border-radius: 9px; ">
      <p>
        <strong>Name:</strong>
        <%= @customer_account.fname + ' ' + @customer_account.middle_initial + ' ' + @customer_account.lname %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= @customer_account.street_add + ', ' + @customer_account.city + ', ' + @customer_account.state + ' ' + @customer_account.zipcode %>
      </p>
      <p>
        <strong>Email:</strong>
        <%= @customer_account.email %>
      </p>

      <p>
        <strong>Home phone:</strong>
        <%= @customer_account.home_phone %>
      </p>

      <p>
        <strong>Cell phone:</strong>
        <%= @customer_account.cell_phone %>
      </p>

      <p>
        <strong>Phone preference:</strong>
        <%= @customer_account.phone_pref %>
      </p>

      <p>
         <%= link_to 'Edit your information', edit_customer_account_path(@customer_account), class: "btn btn-info" %>
      </p>
   </div>

   <div class="col-md-8 col-md-offset-0">
      <br><br>
      <p style="font-size: 2em; ">Would you like to place an order today?</p>
      <br><br>
      <div class="col-md-4 col-md-offset-0">
         <%= link_to "No, thank you", root_path, class: "btn btn-danger btn-block" %>
      </div>
      <div class="col-md-4 col-md-offset-0">
         <%= link_to "yes", new_sales_order_path(@customer_account), class: "btn btn-success btn-block" %>
      </div>
   </div>
</div>

<div class="row">
</div>

<% if false %>
<%= link_to 'Edit', edit_customer_account_path(@customer_account) %> |
<%= link_to 'Back', root_path %>
<% end %>