config/routes.rb
Rails.application.routes.draw do
  resources :so_shipments
  resources :so_pick_lists
  resources :order_lines
  resources :sales_orders
  resources :inventory_items
  resources :order_statuses
  resources :customer_accounts

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'

end

app/models/so_pick_list.rb
class SoPickList < ActiveRecord::Base
  belongs_to :sales_order
  belongs_to :order_line
end

app/controllers/so_pick_lists_controller.rb
class SoPickListsController < ApplicationController
  before_action :set_so_pick_list, only: [:show, :edit, :update, :destroy]
  before_filter :check_for_cancel, :only => [:create, :update]

   def check_for_cancel
     if params[:commit] == "Cancel"
       redirect_to new_so_pick_list_url
     end
   end
   
  # GET /so_pick_lists
  # GET /so_pick_lists.json
  def index
    @so_pick_lists = SoPickList.all
  end

  # GET /so_pick_lists/1
  # GET /so_pick_lists/1.json
  def show
    @so = SalesOrder.where(:id => @so_pick_list.sales_order_id)
    
    @customer = CustomerAccount.where(:id => @so.first.customer_account_id)

    @states_hash = HashWithIndifferentAccess.new({"Alabama"=>"AL", "Alaska"=>"AK", "Arizona"=>"AZ", "Arkansas"=>"AR","California"=>"CA",
     "Colorado"=>"CO", "Connecticut"=>"CT", "Delaware"=>"DE", "District of Columbia"=>"DC",
     "Florida"=>"FL", "Georgia"=>"GA", "Hawaii"=>"HI", "Idaho"=>"ID", "Illinois"=>"IL",
     "Indiana"=>"IN", "Iowa"=>"IA","Kansas"=>"KS", "Kentucky"=>"KY", "Louisiana"=>"LA",
     "Maine"=>"ME","Maryland"=>"MD", "Massachusetts"=>"MA", "Michigan"=>"MI", "Minnesota"=>"MN",
     "Mississippi"=>"MS", "Missouri"=>"MO", "Montana"=>"MT","Nebraska"=>"NE", "Nevada"=>"NV",
     "New Hampshire"=>"NH", "NewJersey"=>"NJ", "New Mexico"=>"NM", "New York"=>"NY",
     "North Carolina"=>"NC", "North Dakota"=>"ND", "Ohio"=>"OH", "Oklahoma"=>"OK",
     "Oregon"=>"OR", "Pennsylvania"=>"PA", "Puerto Rico"=>"PR", "Rhode Island"=>"RI",
     "South Carolina"=>"SC", "South Dakota"=>"SD", "Tennessee"=>"TN", "Texas"=>"TX",
     "Utah"=>"UT", "Vermont"=>"VT", "Virginia"=>"VA", "Washington"=>"WA", "West Virginia"=>"WV",
     "Wisconsin"=>"WI", "Wyoming"=>"WY"})
  end

  # GET /so_pick_lists/new
  def new
    @so_pick_list = SoPickList.new
  end

  # GET /so_pick_lists/1/edit
  def edit
  end

  # POST /so_pick_lists
  # POST /so_pick_lists.json
  def create
    @so_pick_list = SoPickList.new(so_pick_list_params)

    respond_to do |format|
      if @so_pick_list.save
        flash[:success] = "So pick list was successfully created!"
        format.html { redirect_to @so_pick_list }
        format.json { render :show, status: :created, location: @so_pick_list }
      else
        format.html { render :new }
        format.json { render json: @so_pick_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /so_pick_lists/1
  # PATCH/PUT /so_pick_lists/1.json
  def update
    respond_to do |format|
      if @so_pick_list.update(so_pick_list_params)
        flash[:success] = "So pick list was successfully updated!"
        format.html { redirect_to @so_pick_list }
        format.json { render :show, status: :ok, location: @so_pick_list }
      else
        format.html { render :edit }
        format.json { render json: @so_pick_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /so_pick_lists/1
  # DELETE /so_pick_lists/1.json
  def destroy
    @so_pick_list.destroy
    respond_to do |format|
      format.html { redirect_to so_pick_lists_url, notice: 'So pick list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_so_pick_list
      @so_pick_list = SoPickList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def so_pick_list_params
      params.require(:so_pick_list).permit(:sales_order_id, :order_line_id)
    end
end

app/helpers/so_pick_lists_helper.rb
module SoPickListsHelper
end

app/views/so_pick_lists/_form.html.erb
<%= form_for(@so_pick_list) do |f| %>
  <% if @so_pick_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@so_pick_list.errors.count, "error") %> prohibited this so_pick_list from being saved:</h2>

      <ul>
      <% @so_pick_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="col-md-4 col-md-offset-4 pad-10"> 
      <% options = options_from_collection_for_select(SalesOrder.where(:order_status_id => 2), 'id', 'id') %>
      <%= f.select :sales_order_id, options, :input_html => { class: "form-control" } %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-2 col-md-offset-4">
      <%= f.submit "Cancel", class: "btn btn-danger" %>
    </div>
    <div class="col-md-2 col-md-offset-0">
      <button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#myModal">Generate Pick List</button>
    </div>
  </div>

<!-- confirmaiton modal starts here -->
  
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
         <div class="modal-dialog">
            <div class="modal-content" style="font-size: 2em; ">
               <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title" id="myModalLabel">Confirmation</h4>
               </div>
               <div class="modal-body">Are you sure?</div>
               <div class="modal-footer" style="border: none">
                 <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                 <button class="btn btn-success">Yes</button>
               </div>
           </div>
         </div>
      </div>

<% end %>

app/views/so_pick_lists/edit.html.erb
<h1>Editing So Pick List</h1>

<h3>Sales Orders Ready to be Picked</h3>

<table class="table table-striped table-condensed" >
  <thead>
    <tr>
      <th>Sales Order ID</th>
      <th>Customer account</th>
      <th>Placed On</th>
      <th>Order status</th>
    </tr>
  </thead>

  <tbody>
    <% @orders = SalesOrder.where(:order_status_id => 2).limit(8) %>
    
    <% @orders.each do |so| %>  
      <tr>
        <td><%= so.id %></td>
        <td><%= so.customer_account_id %></td>
        <td><%= so.created_at %></td>
        <td>Processed</td>  
      </tr>
    <% end %>
  </tbody>
  
</table>

<br>

<%= render 'form' %>

<%= link_to 'Show', @so_pick_list %> |
<%= link_to 'Back', so_pick_lists_path %>

app/views/so_pick_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sales Orders Ready to be Picked</h1>

<table class="table table-striped table-condensed" >
  <thead>
    <tr>
      <th>Sales Order ID</th>
      <th>Customer account</th>
      <th>Placed On</th>
      <th>Order line</th>
      <th>Order status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders = SalesOrder.where(:order_status_id => 2).limit(8) %>
    
    <% @orders.each do |so| %>  
      <tr>
        <td><%= so.id %></td>
        <td><%= so.customer_account_id %></td>
        <td><%= so.created_at %></td>
        <td><%= so.order_status_id %></td>
        <td><%= so.order_status_id %></td>  
      </tr>
    <% end %>
  </tbody>
  
</table>

<h3>Please select an order to pick</h3>

<%= form_for(@so_pick_list) do |f| %>
  <% if @so_pick_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@so_pick_list.errors.count, "error") %> prohibited this so_pick_list from being saved:</h2>

      <ul>
      <% @so_pick_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'shared/error_messages', object: f.object %>

  <div class="row">
  
  <div class="col-md-6 pad-10"> 
    <% options = options_for_select(SalesOrder.where(:order_status_id => 2), 'id') %>
    <%= f.select :location, options, :input_html => { class: "form-control" } %>
  </div>

<% end %>

<br>

<%= link_to 'New So pick list', new_so_pick_list_path %>

app/views/so_pick_lists/new.html.erb
<p id="notice"><%= notice %></p>

<h1>Sales Orders Ready to be Picked</h1>

<table class="table table-striped table-condensed" >
  <thead>
    <tr>
      <th>Sales Order ID</th>
      <th>Customer account</th>
      <th>Placed On</th>
      <th>Order status</th>
    </tr>
  </thead>

  <tbody>
    <% @orders = SalesOrder.where(:order_status_id => 2).limit(8) %>
    
    <% @orders.each do |so| %>  
      <tr>
        <td><%= so.id %></td>
        <td><%= so.customer_account_id %></td>
        <td><%= so.created_at %></td>
        <td>Processed</td>  
      </tr>
    <% end %>
  </tbody>
  
</table>

<br>

<h3 style="text-align: center; ">Please select an order to pick</h3>

<%= render 'form' %>

<br>

<%= link_to 'Back', root_path %>

app/views/so_pick_lists/show.html.erb
<h6>Shipping address:</h6>

<div class="row">
   <div class="col-md-8 col-md-offset-0">
      <%= @customer.first.fname + ' ' + @customer.first.middle_initial + ' ' + @customer.first.lname %>
   </div>
   <div class="col-md-2 col-md-offset-0 text-right">
      Ordered on:
   </div>
   <div class="col-md-2 col-md-offset-0 text-left">
      <%= @so.first.created_at.to_s[0..9] %>
   </div>
</div>

<div class="row">
   <div class="col-md-8 col-md-offset-0">
      <%= @so.first.shipping_street_address %>
   </div>   
   <div class="col-md-2 col-md-offset-0 text-right">
     Ship by date:
   </div>
   <div class="col-md-2 col-md-offset-0 text-left">
     <% @t = Time.now + 86400 %>
     <%= @t.year.to_s + '-' + @t.month.to_s + '-' + @t.day.to_s %>
   </div>
</div>

<div class="row">
   <div class="col-md-8 col-md-offset-0">
      <%= @so.first.shipping_city + ', ' + @states_hash[@so.first.shipping_state] + ' ' + @so.first.shipping_zipcode %>
   </div>
   <div class="col-md-2 col-md-offset-0 text-right">
      Sales order#:
   </div>
   <div class="col-md-2 col-md-offset-0 text-left">
      <%= @so_pick_list.sales_order.id %>
   </div>
</div>
<br>
<div class="row">
    <div class="col-md-12 text-center">
        <h3>Pick List</h3>
    </div>
</div>

<div class="row">
<table class="table table-striped table-condensed" >
  <thead>
    <tr>
      <th>Aisle</th>
      <th>Area</th>
      <th>Bar code</th>
      <th>Product Name</th>
      <th>Quantity to pick</th>
      <th>Unit of measure</th>
      <th>Unit Price</th>
      <th>Total Price</th>      
    </tr>
  </thead>

  <tbody>
    <% @picklines = OrderLine.where(:sales_order_id => @so_pick_list.sales_order.id) %>
    <% @picklines.each do |line| %>
      <% @item = InventoryItem.where(:id => line.inventory_item_id) %>
      <tr>
        <td><%= @item.first.location_aisle %></td>
        <td><%= @item.first.location_area %></td>
        <td><%= @item.first.barcode %></td>
        <td><%= @item.first.product_name %></td>
        <td><%= line.qty_ordered %></td>                
        <td><%= @item.first.unit_of_measure.pluralize(line.qty_ordered) %></td>
        <td><%= @item.first.selling_price %></td>
        <td><%= (@item.first.selling_price * line.qty_ordered) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="row">
 <div class="col-md-4 col-md-offset-4">
   
   <input class="btn btn-success" type="submit" value="Print Pick List">
 </div>
</div>

<br><br><br>

<div class="row">
   <div class="col-md-12 text-right">
      <div class='btn-group'>
         <%= link_to 'Generate another pick list', new_so_pick_list_path, class: "btn btn-info" %>
         <%= link_to 'Home', root_path, class: "btn btn-success" %>
      </div>
   </div>
</div>

<% if false %>
   <%= link_to 'Edit', edit_so_pick_list_path(@so_pick_list) %> |
   <%= link_to 'Back', new_so_pick_list_path %>
<% end %>