config/routes.rb
Rails.application.routes.draw do
  resources :so_shipments
  resources :so_pick_lists
  resources :order_lines
  resources :sales_orders
  resources :inventory_items
  resources :order_statuses
  resources :customer_accounts

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Global Parts Operations", root_path %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <li><h6><%= image_tag("half_Globe2.gif", alt: "GPO corporate logo", :size => '50x30' )%></h6></li>
        <li><h6><%= link_to "Global Parts Operations", root_path, id: "logo" %></h6></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Create Customer Account", new_customer_account_path %></li>
        <li><%= link_to "Create Sales Order", new_sales_order_path %></li>
        <li><%= link_to "Generate SO Pick List", new_so_pick_list_path %></li>
        <li><%= link_to "Record Shipment of Sales Order", new_so_shipment_path %></li>

            <% if false %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
            <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    
    <%= stylesheet_link_tag 'application', 'thickbox' %>
    <%= javascript_include_tag 'jquery-1.3.2.min', 'jquery.validate.min', 'application' %>
    
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if !Rails.env.development? %>
    </div>
  </body>
</html>